"""Markdown Reporter — basic markdown report rendering.

An HTML reporter ships separately for detailed run reports.
"""

from __future__ import annotations
from datetime import datetime
from pathlib import Path

from ...core.interfaces import Reporter, ReportFormat
from ...core.schemas import Change, Run


class MarkdownReporter:
    name = "markdown"
    formats = ["markdown"]

    def render(self, run: Run, change: Change, format: ReportFormat, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        out = output_dir / f"{run.id}.md"

        status_emoji = {"pass": "✅", "fail": "❌", "blocked": "⚠️", "partial": "🟡"}.get(run.status, "❓")

        lines = [
            f"# Test Report: {change.title}",
            "",
            f"**Status**: {status_emoji} `{run.status.upper()}`",
            f"**Run ID**: `{run.id}`",
            f"**Change**: `{change.id}`",
            f"**Executor**: {run.executor}",
            f"**Headed**: {run.headed}",
            f"**Started**: {run.started_at}",
            f"**Ended**: {run.ended_at}",
            "",
            "## Tasks",
            "",
        ]
        for t in change.tasks:
            mark = "x" if t.done else " "
            lines.append(f"- [{mark}] **{t.id}** {t.text}")

        if run.findings:
            lines += ["", "## Findings", ""]
            for f in run.findings:
                lines += [
                    f"### {f.severity.upper()}: {f.title}",
                    f"- **Category**: {f.category}",
                    f"- **Expected**: {f.expected}",
                    f"- **Actual**: {f.actual}",
                ]
                if f.steps_to_reproduce:
                    lines.append("- **Steps to reproduce**:")
                    for s in f.steps_to_reproduce:
                        lines.append(f"  - {s}")
                if f.evidence:
                    lines.append("- **Evidence**:")
                    for e in f.evidence:
                        lines.append(f"  - {e}")
                lines.append("")

        if run.test_path:
            lines += ["", "## Test File", "", f"`{run.test_path}`", ""]

        if run.notes:
            lines += ["", "## Execution Log", "", "```", run.notes, "```", ""]

        lines += [
            "",
            "---",
            f"_Generated by Evo QA at {datetime.utcnow().isoformat()}_",
        ]

        out.write_text("\n".join(lines))
        return out


__all__ = ["MarkdownReporter"]
