"""Pytest-Playwright TestRunner — render a Change into standalone pytest
files and execute them.

Key design choices:
- Rendered artifacts are **human-readable and standalone** pytest files
  (they continue to run without this skill).
- Jinja2 templates, easy to extend.
- `execute()` invokes pytest as a subprocess and collects the results.
"""

from __future__ import annotations
import json
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Template

from ...core.interfaces import ProjectType, TestRunner
from ...core.schemas import Change, Finding, Run


# Simple inline template; can be moved under templates/ later if desired.
PYTEST_TEMPLATE = '''"""
Auto-generated test from Change: {{ change.id }}
Title: {{ change.title }}
Generated at: {{ generated_at }}

This file is committed and runnable independently with:
    pytest {{ output_filename }} --headed   # watch the browser
    pytest {{ output_filename }}            # headless

Do NOT edit manually unless you also update the source change.
"""
import pytest
from playwright.sync_api import Page, expect


{% for task in change.tasks %}
def test_{{ task.id|replace('.', '_') }}_{{ task.text|to_slug }}(page: Page):
    """{{ task.text }}"""
    {% if task.steps %}
    {% for step in task.steps %}
    {{ step }}
    {% endfor %}
    {% else %}
    # TODO: implement steps for: {{ task.text }}
    pytest.skip("Steps not yet generated for this task")
    {% endif %}
{% endfor %}
'''


def _to_slug(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", s.lower()).strip("_")
    return s[:40] or "step"


class PytestRunner:
    name = "pytest-playwright"
    language = "python"

    def detect_project(self, root: Path) -> ProjectType:
        if (root / "pyproject.toml").exists() or (root / "setup.py").exists():
            return "python-pytest"
        if (root / "package.json").exists():
            try:
                pkg = json.loads((root / "package.json").read_text())
                deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                if "@playwright/test" in deps:
                    return "typescript-playwright"
            except Exception:
                pass
        return "unknown"

    def render(self, change: Change, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        output_filename = f"test_{change.id.replace('-', '_')}.py"
        output_path = output_dir / output_filename

        # Emit a conftest.py once per specs/ dir so pytest-playwright
        # accepts internal-CA URLs (e.g. internal corporate sites).
        # Uses ignore_https_errors=True; safe for QA contexts.
        conftest_path = output_dir / "conftest.py"
        if not conftest_path.exists():
            conftest_path.write_text(
                '"""Auto-generated by Evo QA. Do not edit by hand.\n'
                'Configures pytest-playwright fixtures so internal-CA URLs work."""\n'
                "import pytest\n\n\n"
                "@pytest.fixture(scope=\"session\")\n"
                "def browser_context_args(browser_context_args):\n"
                "    return {**browser_context_args, \"ignore_https_errors\": True}\n"
            )

        from jinja2 import Environment
        env = Environment()
        env.filters["to_slug"] = _to_slug
        tmpl = env.from_string(PYTEST_TEMPLATE)

        rendered = tmpl.render(
            change=change,
            output_filename=output_filename,
            generated_at=datetime.utcnow().isoformat(),
        )
        output_path.write_text(rendered)
        return output_path

    def execute(self, test_path: Path, *, headed: bool = False) -> Run:
        run_id = f"run-{int(time.time())}"
        started = datetime.utcnow().isoformat()

        cmd = [
            sys.executable, "-m", "pytest",
            str(test_path),
            "-v",
            "--tb=short",
            "--color=no",
        ]
        if headed:
            cmd.append("--headed")

        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300,
                cwd=str(test_path.parent),
            )
            stdout = proc.stdout
            stderr = proc.stderr
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            stdout, stderr, rc = "", "TIMEOUT after 300s", 124

        # Lightweight parse of pytest output
        passed = stdout.count(" PASSED")
        failed = stdout.count(" FAILED")
        errored = stdout.count(" ERROR")
        skipped = stdout.count(" SKIPPED")

        if rc == 0 and passed > 0:
            status = "pass"
        elif failed > 0 or errored > 0:
            status = "fail"
        elif skipped > 0 and passed == 0:
            status = "blocked"
        else:
            status = "partial"

        findings: list[Finding] = []
        if status in ("fail", "blocked"):
            findings.append(Finding(
                id=f"f-{run_id}-1",
                severity="high" if status == "fail" else "medium",
                category="functional",
                title=f"{failed + errored} test(s) failed",
                steps_to_reproduce=[f"Run: {' '.join(cmd)}"],
                expected="All tests pass",
                actual=f"{passed} passed / {failed} failed / {errored} errored / {skipped} skipped",
                evidence=[],
            ))

        return Run(
            id=run_id,
            change_id="",  # caller fills
            started_at=started,
            ended_at=datetime.utcnow().isoformat(),
            status=status,
            executor="pytest-playwright",
            test_path=str(test_path),
            trace_path="",
            headed=headed,
            findings=findings,
            notes=f"Returncode={rc}\n\n--- STDOUT ---\n{stdout[-3000:]}\n\n--- STDERR ---\n{stderr[-1000:]}",
        )


__all__ = ["PytestRunner"]
